### ISSUE TITLE
💖 the screenshot in your readme!  

### ISSUE THREAD

**Issue by PySimpleGUI** [guansanghai/KoiKoi-AI#1]
Very nice job of putting a screenshot in your readme.  It looks GREAT!  What a beautiful window you've made.... _**beatiful**_

Because it's a game and thus has an interface that changes often, it may work even better to have a GIF animation.... not that there's anything at ALL wrong or missing from what you've done!  It's fantastic. 

I use ShareX (https://getsharex.com/) to make animated GIFs.  I don't know how this program makes TINY GIFs from large in size and length animations, but it does.

Here's one I made a while back and I simply copied and pasted into a GitHub Issue.... like I did here:

![notepad](https://user-images.githubusercontent.com/46163555/109364850-b9d57d80-785d-11eb-85ed-0ccf75073a04.gif)

**Comment by guansanghai** [comment]
Very good suggestion, I have replaced it with a GIF :)

**Comment by PySimpleGUI** [comment]
OOOOOOOOooooooooooooooooooooooooo!!!!

I LOVE IT!

That's NICE!

Thank you SO much for adding it!

![image](https://user-images.githubusercontent.com/46163555/133818555-68590116-9aac-4783-b276-e6d49840965a.png)
